package com.driverdata.chenxi.dal.model;

import java.util.Date;

public class InstanceAssociDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.gmt_create
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.gmt_modified
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.is_deleted
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.creator
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.modifier
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.node
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Integer node;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.node2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Integer node2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.type2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private String type2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column i_associ.associ_type_id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    private Integer associTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.id
     *
     * @return the value of i_associ.id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.id
     *
     * @param id the value for i_associ.id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.gmt_create
     *
     * @return the value of i_associ.gmt_create
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.gmt_create
     *
     * @param gmtCreate the value for i_associ.gmt_create
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.gmt_modified
     *
     * @return the value of i_associ.gmt_modified
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.gmt_modified
     *
     * @param gmtModified the value for i_associ.gmt_modified
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.is_deleted
     *
     * @return the value of i_associ.is_deleted
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.is_deleted
     *
     * @param isDeleted the value for i_associ.is_deleted
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.creator
     *
     * @return the value of i_associ.creator
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.creator
     *
     * @param creator the value for i_associ.creator
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.modifier
     *
     * @return the value of i_associ.modifier
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.modifier
     *
     * @param modifier the value for i_associ.modifier
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.node
     *
     * @return the value of i_associ.node
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Integer getNode() {
        return node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.node
     *
     * @param node the value for i_associ.node
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setNode(Integer node) {
        this.node = node;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.node2
     *
     * @return the value of i_associ.node2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Integer getNode2() {
        return node2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.node2
     *
     * @param node2 the value for i_associ.node2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setNode2(Integer node2) {
        this.node2 = node2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.type
     *
     * @return the value of i_associ.type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.type
     *
     * @param type the value for i_associ.type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.type2
     *
     * @return the value of i_associ.type2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public String getType2() {
        return type2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.type2
     *
     * @param type2 the value for i_associ.type2
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setType2(String type2) {
        this.type2 = type2 == null ? null : type2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column i_associ.associ_type_id
     *
     * @return the value of i_associ.associ_type_id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public Integer getAssociTypeId() {
        return associTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column i_associ.associ_type_id
     *
     * @param associTypeId the value for i_associ.associ_type_id
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    public void setAssociTypeId(Integer associTypeId) {
        this.associTypeId = associTypeId;
    }
}