package com.bk.chenxi.dal.mapper;

import com.bk.chenxi.dal.model.InstanceDo;
import com.bk.chenxi.dal.model.InstanceDoExample;
import java.util.List;

public interface InstanceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int countByExample(InstanceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int deleteByPrimaryKey(InstanceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int insertSelective(InstanceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    List<InstanceDo> selectByExample(InstanceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    InstanceDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int updateByPrimaryKeySelective(InstanceDo record);
}