package com.bk.chenxi.dal.mapper;

import com.bk.chenxi.dal.model.InstanceDependDo;
import com.bk.chenxi.dal.model.InstanceDependDoExample;
import java.util.List;

public interface InstanceDependDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int countByExample(InstanceDependDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int deleteByPrimaryKey(InstanceDependDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int insertSelective(InstanceDependDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    List<InstanceDependDo> selectByExample(InstanceDependDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    InstanceDependDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table i_depend
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int updateByPrimaryKeySelective(InstanceDependDo record);
}