package com.bk.chenxi.dal.mapper;

import com.bk.chenxi.dal.model.UserRoleDo;
import com.bk.chenxi.dal.model.UserRoleDoExample;
import java.util.List;

public interface UserRoleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int countByExample(UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int deleteByPrimaryKey(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int insertSelective(UserRoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    List<UserRoleDo> selectByExample(UserRoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    UserRoleDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    int updateByPrimaryKeySelective(UserRoleDo record);
}