package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.DicSettingDo;
import com.driverdata.chenxi.dal.model.DicSettingDoExample;
import java.util.List;

public interface DicSettingDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int countByExample(DicSettingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int deleteByPrimaryKey(DicSettingDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int insertSelective(DicSettingDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    List<DicSettingDo> selectByExample(DicSettingDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    DicSettingDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictionary_setting
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int updateByPrimaryKeySelective(DicSettingDo record);
}