package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.EntityDo;
import com.driverdata.chenxi.dal.model.EntityDoExample;
import java.util.List;

public interface EntityDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int countByExample(EntityDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int deleteByPrimaryKey(EntityDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int insertSelective(EntityDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    List<EntityDo> selectByExample(EntityDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    EntityDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table entity
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int updateByPrimaryKeySelective(EntityDo record);
}