package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.FieldDataTypeDo;
import com.driverdata.chenxi.dal.model.FieldDataTypeDoExample;
import java.util.List;

public interface FieldDataTypeDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int countByExample(FieldDataTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int deleteByPrimaryKey(FieldDataTypeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int insertSelective(FieldDataTypeDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    List<FieldDataTypeDo> selectByExample(FieldDataTypeDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    FieldDataTypeDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field_data_type
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int updateByPrimaryKeySelective(FieldDataTypeDo record);
}