package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.FieldDo;
import com.driverdata.chenxi.dal.model.FieldDoExample;
import java.util.List;

public interface FieldDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int countByExample(FieldDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int deleteByPrimaryKey(FieldDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int insertSelective(FieldDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    List<FieldDo> selectByExample(FieldDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    FieldDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table field
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int updateByPrimaryKeySelective(FieldDo record);
}