package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.InstanceDo;
import com.driverdata.chenxi.dal.model.InstanceDoExample;
import java.util.List;

public interface InstanceDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int countByExample(InstanceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int deleteByPrimaryKey(InstanceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int insertSelective(InstanceDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    List<InstanceDo> selectByExample(InstanceDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    InstanceDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instance
     *
     * @mbggenerated Fri May 27 13:14:02 CST 2016
     */
    int updateByPrimaryKeySelective(InstanceDo record);
}