package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface OrganizationDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    int countByExample(OrganizationDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    int deleteByPrimaryKey(OrganizationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    int insertSelective(OrganizationDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    List<OrganizationDo> selectByExample(OrganizationDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    OrganizationDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbggenerated Tue Nov 24 19:36:57 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(OrganizationDo record);
}