package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.PermissionDo;
import com.driverdata.chenxi.dal.model.PermissionDoExample;
import java.util.List;

public interface PermissionDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int countByExample(PermissionDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int deleteByPrimaryKey(PermissionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int insertSelective(PermissionDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    List<PermissionDo> selectByExample(PermissionDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    PermissionDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PermissionDo record);
}