package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProDeliveryLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProDeliveryLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProDeliveryLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProDeliveryLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProDeliveryLogDo> selectByExample(ProDeliveryLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProDeliveryLogDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_delivery_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProDeliveryLogDo record);
}