package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectDo> selectByExample(ProjectDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectDo record);
}