package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectHasDictionaryDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectHasDictionaryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectHasDictionaryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectHasDictionaryDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectHasDictionaryDo> selectByExample(ProjectHasDictionaryDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectHasDictionaryDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_has_dictionary
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectHasDictionaryDo record);
}