package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectEventDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectEventDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectEventDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectEventDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectEventDo> selectByExample(ProjectEventDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectEventDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_event
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectEventDo record);
}