package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectTeamMemberDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectTeamMemberDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectTeamMemberDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectTeamMemberDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectTeamMemberDo> selectByExample(ProjectTeamMemberDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectTeamMemberDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_team_member
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectTeamMemberDo record);
}