package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectAuditLogDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectAuditLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectAuditLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectAuditLogDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectAuditLogDo> selectByExample(ProjectAuditLogDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectAuditLogDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_audit_log
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectAuditLogDo record);
}