package com.driverdata.chenxi.dal.mapper;

import java.util.List;

public interface ProjectShareholdingStructureDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int countByExample(ProjectShareholdingStructureDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(ProjectShareholdingStructureDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int insertSelective(ProjectShareholdingStructureDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    List<ProjectShareholdingStructureDo> selectByExample(ProjectShareholdingStructureDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    ProjectShareholdingStructureDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_shareholding_structure
     *
     * @mbggenerated Thu Nov 05 17:28:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ProjectShareholdingStructureDo record);
}