package com.driverdata.chenxi.dal.mapper;

import com.driverdata.chenxi.dal.model.RoleDo;
import com.driverdata.chenxi.dal.model.RoleDoExample;
import java.util.List;

public interface RoleDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int countByExample(RoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int deleteByPrimaryKey(RoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int insertSelective(RoleDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    List<RoleDo> selectByExample(RoleDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    RoleDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated Tue Nov 10 18:23:38 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RoleDo record);
}