package com.bk.chenxi.dal.model;

import java.util.Date;

public class FileDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer associateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.id
     *
     * @return the value of file.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.id
     *
     * @param id the value for file.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.type
     *
     * @return the value of file.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.type
     *
     * @param type the value for file.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.url
     *
     * @return the value of file.url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.url
     *
     * @param url the value for file.url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.name
     *
     * @return the value of file.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.name
     *
     * @param name the value for file.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.associate_id
     *
     * @return the value of file.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getAssociateId() {
        return associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.associate_id
     *
     * @param associateId the value for file.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setAssociateId(Integer associateId) {
        this.associateId = associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.gmt_create
     *
     * @return the value of file.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.gmt_create
     *
     * @param gmtCreate the value for file.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.gmt_modified
     *
     * @return the value of file.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.gmt_modified
     *
     * @param gmtModified the value for file.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.creator
     *
     * @return the value of file.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.creator
     *
     * @param creator the value for file.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.modifier
     *
     * @return the value of file.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.modifier
     *
     * @param modifier the value for file.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.is_deleted
     *
     * @return the value of file.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.is_deleted
     *
     * @param isDeleted the value for file.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}