package com.bk.chenxi.dal.model;

import java.util.Date;

public class ImageDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer associateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.original_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String originalUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.thumbnail_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String thumbnailUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.my_order
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer myOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.mobile_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String mobileUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.gmt_create
     *
     * @return the value of image.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.gmt_create
     *
     * @param gmtCreate the value for image.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.gmt_modified
     *
     * @return the value of image.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.gmt_modified
     *
     * @param gmtModified the value for image.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.type
     *
     * @return the value of image.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.type
     *
     * @param type the value for image.type
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.associate_id
     *
     * @return the value of image.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getAssociateId() {
        return associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.associate_id
     *
     * @param associateId the value for image.associate_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setAssociateId(Integer associateId) {
        this.associateId = associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.original_url
     *
     * @return the value of image.original_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getOriginalUrl() {
        return originalUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.original_url
     *
     * @param originalUrl the value for image.original_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl == null ? null : originalUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.thumbnail_url
     *
     * @return the value of image.thumbnail_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.thumbnail_url
     *
     * @param thumbnailUrl the value for image.thumbnail_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl == null ? null : thumbnailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.is_deleted
     *
     * @return the value of image.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.is_deleted
     *
     * @param isDeleted the value for image.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.creator
     *
     * @return the value of image.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.creator
     *
     * @param creator the value for image.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.modifier
     *
     * @return the value of image.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.modifier
     *
     * @param modifier the value for image.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.name
     *
     * @return the value of image.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.name
     *
     * @param name the value for image.name
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.my_order
     *
     * @return the value of image.my_order
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getMyOrder() {
        return myOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.my_order
     *
     * @param myOrder the value for image.my_order
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setMyOrder(Integer myOrder) {
        this.myOrder = myOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.mobile_url
     *
     * @return the value of image.mobile_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getMobileUrl() {
        return mobileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.mobile_url
     *
     * @param mobileUrl the value for image.mobile_url
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setMobileUrl(String mobileUrl) {
        this.mobileUrl = mobileUrl == null ? null : mobileUrl.trim();
    }
}