package com.bk.chenxi.dal.model;

import java.util.Date;

public class InstanceDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.entity_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.entity_key
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String entityKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column1
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column2
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column3
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column4
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column5
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column6
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column7
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column8
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column9
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column10
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column11
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column12
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column13
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column14
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column15
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column16
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column16;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column17
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column17;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column18
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column19
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column19;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column20
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column20;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column21
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column21;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column22
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column22;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column23
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column23;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column24
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column24;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column25
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column26
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column26;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column27
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column27;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column28
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column28;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column29
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column29;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column30
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column30;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column31
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column31;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column32
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column32;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column33
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column33;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column34
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column34;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column35
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column35;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column36
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column36;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column37
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column37;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column38
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column38;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column39
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column39;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column40
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column40;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column41
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date column41;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column42
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date column42;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column43
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date column43;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column44
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date column44;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column45
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private Date column45;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column46
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column46;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column47
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column47;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column48
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column48;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column49
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column49;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instance.column50
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    private String column50;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.id
     *
     * @return the value of instance.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.id
     *
     * @param id the value for instance.id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.gmt_create
     *
     * @return the value of instance.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.gmt_create
     *
     * @param gmtCreate the value for instance.gmt_create
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.gmt_modified
     *
     * @return the value of instance.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.gmt_modified
     *
     * @param gmtModified the value for instance.gmt_modified
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.is_deleted
     *
     * @return the value of instance.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.is_deleted
     *
     * @param isDeleted the value for instance.is_deleted
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.creator
     *
     * @return the value of instance.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.creator
     *
     * @param creator the value for instance.creator
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.modifier
     *
     * @return the value of instance.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.modifier
     *
     * @param modifier the value for instance.modifier
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.entity_id
     *
     * @return the value of instance.entity_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.entity_id
     *
     * @param entityId the value for instance.entity_id
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.entity_key
     *
     * @return the value of instance.entity_key
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getEntityKey() {
        return entityKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.entity_key
     *
     * @param entityKey the value for instance.entity_key
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setEntityKey(String entityKey) {
        this.entityKey = entityKey == null ? null : entityKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column1
     *
     * @return the value of instance.column1
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn1() {
        return column1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column1
     *
     * @param column1 the value for instance.column1
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn1(String column1) {
        this.column1 = column1 == null ? null : column1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column2
     *
     * @return the value of instance.column2
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn2() {
        return column2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column2
     *
     * @param column2 the value for instance.column2
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn2(String column2) {
        this.column2 = column2 == null ? null : column2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column3
     *
     * @return the value of instance.column3
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn3() {
        return column3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column3
     *
     * @param column3 the value for instance.column3
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn3(String column3) {
        this.column3 = column3 == null ? null : column3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column4
     *
     * @return the value of instance.column4
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn4() {
        return column4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column4
     *
     * @param column4 the value for instance.column4
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn4(String column4) {
        this.column4 = column4 == null ? null : column4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column5
     *
     * @return the value of instance.column5
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn5() {
        return column5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column5
     *
     * @param column5 the value for instance.column5
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn5(String column5) {
        this.column5 = column5 == null ? null : column5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column6
     *
     * @return the value of instance.column6
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn6() {
        return column6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column6
     *
     * @param column6 the value for instance.column6
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn6(String column6) {
        this.column6 = column6 == null ? null : column6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column7
     *
     * @return the value of instance.column7
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn7() {
        return column7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column7
     *
     * @param column7 the value for instance.column7
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn7(String column7) {
        this.column7 = column7 == null ? null : column7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column8
     *
     * @return the value of instance.column8
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn8() {
        return column8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column8
     *
     * @param column8 the value for instance.column8
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn8(String column8) {
        this.column8 = column8 == null ? null : column8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column9
     *
     * @return the value of instance.column9
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn9() {
        return column9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column9
     *
     * @param column9 the value for instance.column9
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn9(String column9) {
        this.column9 = column9 == null ? null : column9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column10
     *
     * @return the value of instance.column10
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn10() {
        return column10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column10
     *
     * @param column10 the value for instance.column10
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn10(String column10) {
        this.column10 = column10 == null ? null : column10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column11
     *
     * @return the value of instance.column11
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn11() {
        return column11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column11
     *
     * @param column11 the value for instance.column11
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn11(String column11) {
        this.column11 = column11 == null ? null : column11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column12
     *
     * @return the value of instance.column12
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn12() {
        return column12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column12
     *
     * @param column12 the value for instance.column12
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn12(String column12) {
        this.column12 = column12 == null ? null : column12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column13
     *
     * @return the value of instance.column13
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn13() {
        return column13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column13
     *
     * @param column13 the value for instance.column13
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn13(String column13) {
        this.column13 = column13 == null ? null : column13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column14
     *
     * @return the value of instance.column14
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn14() {
        return column14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column14
     *
     * @param column14 the value for instance.column14
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn14(String column14) {
        this.column14 = column14 == null ? null : column14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column15
     *
     * @return the value of instance.column15
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn15() {
        return column15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column15
     *
     * @param column15 the value for instance.column15
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn15(String column15) {
        this.column15 = column15 == null ? null : column15.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column16
     *
     * @return the value of instance.column16
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn16() {
        return column16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column16
     *
     * @param column16 the value for instance.column16
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn16(String column16) {
        this.column16 = column16 == null ? null : column16.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column17
     *
     * @return the value of instance.column17
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn17() {
        return column17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column17
     *
     * @param column17 the value for instance.column17
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn17(String column17) {
        this.column17 = column17 == null ? null : column17.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column18
     *
     * @return the value of instance.column18
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn18() {
        return column18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column18
     *
     * @param column18 the value for instance.column18
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn18(String column18) {
        this.column18 = column18 == null ? null : column18.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column19
     *
     * @return the value of instance.column19
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn19() {
        return column19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column19
     *
     * @param column19 the value for instance.column19
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn19(String column19) {
        this.column19 = column19 == null ? null : column19.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column20
     *
     * @return the value of instance.column20
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn20() {
        return column20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column20
     *
     * @param column20 the value for instance.column20
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn20(String column20) {
        this.column20 = column20 == null ? null : column20.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column21
     *
     * @return the value of instance.column21
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn21() {
        return column21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column21
     *
     * @param column21 the value for instance.column21
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn21(String column21) {
        this.column21 = column21 == null ? null : column21.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column22
     *
     * @return the value of instance.column22
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn22() {
        return column22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column22
     *
     * @param column22 the value for instance.column22
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn22(String column22) {
        this.column22 = column22 == null ? null : column22.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column23
     *
     * @return the value of instance.column23
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn23() {
        return column23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column23
     *
     * @param column23 the value for instance.column23
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn23(String column23) {
        this.column23 = column23 == null ? null : column23.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column24
     *
     * @return the value of instance.column24
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn24() {
        return column24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column24
     *
     * @param column24 the value for instance.column24
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn24(String column24) {
        this.column24 = column24 == null ? null : column24.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column25
     *
     * @return the value of instance.column25
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn25() {
        return column25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column25
     *
     * @param column25 the value for instance.column25
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn25(String column25) {
        this.column25 = column25 == null ? null : column25.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column26
     *
     * @return the value of instance.column26
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn26() {
        return column26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column26
     *
     * @param column26 the value for instance.column26
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn26(String column26) {
        this.column26 = column26 == null ? null : column26.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column27
     *
     * @return the value of instance.column27
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn27() {
        return column27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column27
     *
     * @param column27 the value for instance.column27
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn27(String column27) {
        this.column27 = column27 == null ? null : column27.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column28
     *
     * @return the value of instance.column28
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn28() {
        return column28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column28
     *
     * @param column28 the value for instance.column28
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn28(String column28) {
        this.column28 = column28 == null ? null : column28.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column29
     *
     * @return the value of instance.column29
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn29() {
        return column29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column29
     *
     * @param column29 the value for instance.column29
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn29(String column29) {
        this.column29 = column29 == null ? null : column29.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column30
     *
     * @return the value of instance.column30
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn30() {
        return column30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column30
     *
     * @param column30 the value for instance.column30
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn30(String column30) {
        this.column30 = column30 == null ? null : column30.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column31
     *
     * @return the value of instance.column31
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn31() {
        return column31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column31
     *
     * @param column31 the value for instance.column31
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn31(String column31) {
        this.column31 = column31 == null ? null : column31.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column32
     *
     * @return the value of instance.column32
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn32() {
        return column32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column32
     *
     * @param column32 the value for instance.column32
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn32(String column32) {
        this.column32 = column32 == null ? null : column32.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column33
     *
     * @return the value of instance.column33
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn33() {
        return column33;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column33
     *
     * @param column33 the value for instance.column33
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn33(String column33) {
        this.column33 = column33 == null ? null : column33.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column34
     *
     * @return the value of instance.column34
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn34() {
        return column34;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column34
     *
     * @param column34 the value for instance.column34
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn34(String column34) {
        this.column34 = column34 == null ? null : column34.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column35
     *
     * @return the value of instance.column35
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn35() {
        return column35;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column35
     *
     * @param column35 the value for instance.column35
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn35(String column35) {
        this.column35 = column35 == null ? null : column35.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column36
     *
     * @return the value of instance.column36
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn36() {
        return column36;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column36
     *
     * @param column36 the value for instance.column36
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn36(String column36) {
        this.column36 = column36 == null ? null : column36.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column37
     *
     * @return the value of instance.column37
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn37() {
        return column37;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column37
     *
     * @param column37 the value for instance.column37
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn37(String column37) {
        this.column37 = column37 == null ? null : column37.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column38
     *
     * @return the value of instance.column38
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn38() {
        return column38;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column38
     *
     * @param column38 the value for instance.column38
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn38(String column38) {
        this.column38 = column38 == null ? null : column38.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column39
     *
     * @return the value of instance.column39
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn39() {
        return column39;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column39
     *
     * @param column39 the value for instance.column39
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn39(String column39) {
        this.column39 = column39 == null ? null : column39.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column40
     *
     * @return the value of instance.column40
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn40() {
        return column40;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column40
     *
     * @param column40 the value for instance.column40
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn40(String column40) {
        this.column40 = column40 == null ? null : column40.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column41
     *
     * @return the value of instance.column41
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getColumn41() {
        return column41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column41
     *
     * @param column41 the value for instance.column41
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn41(Date column41) {
        this.column41 = column41;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column42
     *
     * @return the value of instance.column42
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getColumn42() {
        return column42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column42
     *
     * @param column42 the value for instance.column42
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn42(Date column42) {
        this.column42 = column42;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column43
     *
     * @return the value of instance.column43
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getColumn43() {
        return column43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column43
     *
     * @param column43 the value for instance.column43
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn43(Date column43) {
        this.column43 = column43;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column44
     *
     * @return the value of instance.column44
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getColumn44() {
        return column44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column44
     *
     * @param column44 the value for instance.column44
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn44(Date column44) {
        this.column44 = column44;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column45
     *
     * @return the value of instance.column45
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public Date getColumn45() {
        return column45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column45
     *
     * @param column45 the value for instance.column45
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn45(Date column45) {
        this.column45 = column45;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column46
     *
     * @return the value of instance.column46
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn46() {
        return column46;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column46
     *
     * @param column46 the value for instance.column46
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn46(String column46) {
        this.column46 = column46 == null ? null : column46.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column47
     *
     * @return the value of instance.column47
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn47() {
        return column47;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column47
     *
     * @param column47 the value for instance.column47
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn47(String column47) {
        this.column47 = column47 == null ? null : column47.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column48
     *
     * @return the value of instance.column48
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn48() {
        return column48;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column48
     *
     * @param column48 the value for instance.column48
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn48(String column48) {
        this.column48 = column48 == null ? null : column48.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column49
     *
     * @return the value of instance.column49
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn49() {
        return column49;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column49
     *
     * @param column49 the value for instance.column49
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn49(String column49) {
        this.column49 = column49 == null ? null : column49.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instance.column50
     *
     * @return the value of instance.column50
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public String getColumn50() {
        return column50;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instance.column50
     *
     * @param column50 the value for instance.column50
     *
     * @mbggenerated Mon Jun 06 01:23:01 CST 2016
     */
    public void setColumn50(String column50) {
        this.column50 = column50 == null ? null : column50.trim();
    }
}