package com.bk.chenxi.dal.model;

import java.util.Date;

public class MessageDo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.gmt_create
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.gmt_modified
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.creator
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.modifier
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_deleted
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiver
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.business_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String businessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.project_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private Integer projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.user_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sender
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.receiver_address
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String receiverAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.associate_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private Integer associateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_create
     *
     * @return the value of message.gmt_create
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_create
     *
     * @param gmtCreate the value for message.gmt_create
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.gmt_modified
     *
     * @return the value of message.gmt_modified
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.gmt_modified
     *
     * @param gmtModified the value for message.gmt_modified
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.creator
     *
     * @return the value of message.creator
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.creator
     *
     * @param creator the value for message.creator
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.modifier
     *
     * @return the value of message.modifier
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.modifier
     *
     * @param modifier the value for message.modifier
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_deleted
     *
     * @return the value of message.is_deleted
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_deleted
     *
     * @param isDeleted the value for message.is_deleted
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiver
     *
     * @return the value of message.receiver
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiver
     *
     * @param receiver the value for message.receiver
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.business_type
     *
     * @return the value of message.business_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.business_type
     *
     * @param businessType the value for message.business_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message_type
     *
     * @return the value of message.message_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message_type
     *
     * @param messageType the value for message.message_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.project_id
     *
     * @return the value of message.project_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.project_id
     *
     * @param projectId the value for message.project_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.user_type
     *
     * @return the value of message.user_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.user_type
     *
     * @param userType the value for message.user_type
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sender
     *
     * @return the value of message.sender
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sender
     *
     * @param sender the value for message.sender
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.receiver_address
     *
     * @return the value of message.receiver_address
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getReceiverAddress() {
        return receiverAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.receiver_address
     *
     * @param receiverAddress the value for message.receiver_address
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setReceiverAddress(String receiverAddress) {
        this.receiverAddress = receiverAddress == null ? null : receiverAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.associate_id
     *
     * @return the value of message.associate_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public Integer getAssociateId() {
        return associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.associate_id
     *
     * @param associateId the value for message.associate_id
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setAssociateId(Integer associateId) {
        this.associateId = associateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Wed Nov 18 09:55:56 GMT+08:00 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}